name: cleanup

on:
  workflow_dispatch:
    inputs:
      days:
        description: "days to keep"
        required: true
        default: 1
        type: number

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      CLEANUP_DAYS: ${{ inputs.days }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: "24"
      - run: |
          node .github/scripts/cleanup-runs.mts
      - run: |
          node .github/scripts/cleanup-caches.mts
