name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025-vs2026
            arch: x64
          - os: macos-26
            arch: arm64
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: "24.18"
      - uses: actions/cache@v6.1.0
        with:
          key: cache-${{ runner.os }}-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            cache-${{ runner.os }}-${{ matrix.arch }}-
          path: |
            cache
      - run: |
          vcpkg version
      - run: |
          npm ci
      - run: |
          npm run setup-native
      - run: |
          npm run setup-electron
      - run: |
          npm run b
      - run: |
          npm run p
      - uses: softprops/action-gh-release@v3.0.2
        with:
          name: ${{ github.ref_name }}
          draft: true
          prerelease: true
          files: dist/*.tar.gz
