name: test

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025-vs2026
            arch: x64
          - os: macos-26
            arch: arm64
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: "24"
      - uses: actions/cache@v5
        with:
          key: cache-${{ runner.os }}-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            cache-${{ runner.os }}-${{ matrix.arch }}-
          path: |
            cache
      - run: |
          vcpkg version
      - run: |
          npm ci
      - run: |
          npm run setup-native
      - run: |
          npm run setup-electron
      - run: |
          node pkg/native/scripts/cmake_node.mts
      - run: |
          npx fixture
          npx tsx pkg/native/test/test_compare.mts
          npx tsx pkg/native/test/test_get.mts
          npx tsx pkg/native/test/test_icon.mts
          npx tsx pkg/native/test/test_link.mts
          npx tsx pkg/native/test/test_operation.mts
          npx tsx pkg/native/test/test_depth.mts
          npx tsx pkg/native/test/test_os.mts
          npx tsx pkg/native/test/test_arc.mts
          npx tsx pkg/native/test/test_arc_tar.mts
          npx tsx pkg/native/test/test_arc_tarzst.mts
          npx tsx pkg/native/test/test_arc_tgz.mts
          npx tsx pkg/native/test/test_arc_zip.mts
          npx tsx pkg/native/test/test_arc_rar.mts
          npx tsx pkg/native/test/test_arc_rar_pw1.mts
          npx tsx pkg/native/test/test_arc_rar_pw2.mts
          npx tsx pkg/native/test/test_watch.mts
      - run: |
          npm run b
      - run: |
          npm run p
